INSERT INTO account (ID,CHECKING,CHECKING_AMOUNT,SAVING_AMOUNT,SAVINGS) values (1,true,100,300,false);
INSERT INTO account (ID,CHECKING,CHECKING_AMOUNT,SAVING_AMOUNT,SAVINGS) values (2,true,150,250,false);
INSERT INTO account (ID,CHECKING,CHECKING_AMOUNT,SAVING_AMOUNT,SAVINGS) values (3,true,50,500,false);
INSERT INTO account (ID,CHECKING,CHECKING_AMOUNT,SAVING_AMOUNT,SAVINGS) values (4,true,350,100,false);